version: "3.9"

services:
  pharmacy_db:
    image: postgres:15-alpine
    container_name: pharmacy_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=kdan
      - POSTGRES_PASSWORD=kdan
      - POSTGRES_DB=kdan
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - kdan

  pharmacy_api:
    build:
      context: ./pharmacy_backend
      dockerfile: Dockerfile
    container_name: pharmacy_api
    ports:
      - "3000:3000"
    volumes:
      - ./pharmacy_backend:/rails
    depends_on:
      - pharmacy_db
    networks:
      - kdan

networks:
  kdan:
    driver: bridge
